algoritmo " Subtração_com_for"
// Função :
// Autor :
// Data : 16/04/2024
// Seção de Declarações
var
valor1,valor2,contador,subtracao:inteiro

inicio
contador <- 1
para contador de 1 ate 3 faca
   escreva("Digite o 1° valor: ")
   leia(valor1)
   escreva("Digite o 2° valor: ")
   leia(valor2)

   subtracao <- valor1 - valor2
fimpara
//printar resultados
para contador de 1 ate 3 faca
   escreval("Resultado da subtração =",subtracao)
fimpara

fimalgoritmo

