algoritmo "Questão 2 - Idade"
// Função :
// Autor :
// Data : 13/04/2024
// Seção de Declarações 
var
idade: inteiro
inicio
// Seção de Comandos
escreva("Digite sua idade: ")
leia(idade)
se (idade <= 10) entao
   escreval("Você é criança.")
fimse
se (idade > 10) e (idade < 18) entao
   escreval("Você é adolescente.")
fimse
se (idade >= 18) e (idade < 60) entao
   escreval("Você é adulto.")
fimse
se (idade >= 60) entao
   escreval("Você é idoso(a).")
fimse



fimalgoritmo
